### ISSUE TITLE
Add link to the Guitar site

### ISSUE THREAD

**Issue by pmarsceill** [aaronshekey/aaronshekey.com#13]
I noticed there isn't a link to the microsite that you will make for your guitar, yet. When that site goes live, you should probably add a link to it here:

![screenshot 2016-05-02 13 38 23](https://cloud.githubusercontent.com/assets/896475/14962111/291ea8ca-106b-11e6-9ffc-577985270ace.png)

**Comment by aaronshekey** [comment]
Pull requests welcome!

**Comment by jglovier** [comment]
@aaronshekey be careful what you wish for....

![image](https://cloud.githubusercontent.com/assets/1319791/14966866/8b77c13e-1082-11e6-9cb4-dda00407a2f0.png)

**Comment by pmarsceill** [comment]
Helllll yeah!!

**Comment by aaronshekey** [comment]
> Helllll yeah!!

Microsite comin' soon 😉
